### ISSUE TITLE
Socket filename incorrect

### ISSUE THREAD

**Issue by Kriechi** [Duet3D/dsf-python#9]
@mfs12 looks like https://github.com/Duet3D/dsf-python/commit/15accc1d10365783638c19427f01ebbe06ca8c31 introduced a major bug with a wrong socket filename. The python API is currently not working at all because it can't find the DCS socket file.

The correct path is (and was) `/run/dsf/dcs.sock` -- see https://github.com/Duet3D/DuetSoftwareFramework/blob/v3.3-dev/src/DuetAPI/Connection/Defaults.cs#L26
Not `dsf.sock`.

**Comment by mfs12** [comment]
@Kriechi i thought i fixed that... sorry.

Thanks for testing and reporting.
